name: Acquire activation file # Unityのbuildをするために、ライセンスを設定する
on: # このActionsを実行するタイミングの指定（push時、pullreq時など）
  workflow_dispatch: {} # workflow_dispatchは手動で実行ボタンを押したときに実行される　
jobs:
  activation:  # GameCI の Activation を利用して alf ファイルを発行する
    name: Request manual activation file
    runs-on: ubuntu-latest # 動作するosを制作する ubuntuはLinuxOSらしい
    steps:
    - name: Request manual activation file # Licenceを要求する部分
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2
      with: 
      # Unity プロジェクトのバージョンを指定する
        unityVersion: 2021.3.23f1
    - name: Expose as artifact #取得した.alfファイルをアップロードする部分
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ steps.getManualLicensFile.outputs.filePath }}
        path: ${{ steps.getManualLicensFile.outputs.filePath }}
